### ISSUE TITLE
Improve phantomjs uploads to support direct binary uploads

### ISSUE THREAD

**Issue by manthey** [girder/girder#1034]
When we run tests using phantomjs FormData elements, we can't safely upload non-ASCII characters (including simple control characters such as newline).  We can upload binary files via `girdertest.binaryUpload`, but not via `girdertest.testUpload`.

This is caused by how `FormData` is transmitted -- binary characters can be altered if they are passed as simple elements.  A simple substitution of the 'chunk' string with a Blob didn't work, but that is probably what would be necessary.  This may be a limitation in phantomjs, and if we upgrade to phantomjs 2.x, they have had some issues related to this that may affect the solution.

**Comment by jbeezley** [comment]
I believe this issue is resolved in recent versions of phantomjs.  There is even an npm package available ([phantomjs-prebuilt](https://www.npmjs.com/package/phantomjs-prebuilt)) for recent binaries.

I attempted to update to the latest version in my [phantomjs-2.0 branch](https://github.com/girder/girder/tree/phantomjs-2.0), but there is an issue with the jasmine runner + blanket instrumentation that doesn't look very easy to fix.  Updating to jasmine 2.0 may help but I'm not sure.  Another option is to wait for webpackification and use a test runner like karma + istanbul for code coverage.

**Comment by manthey** [comment]
This is stale and may have been fixed.  The new test harness that will come along will obviate its need in any case.
