### ISSUE TITLE
Use Bower for client-side dependencies

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1049]
Bower is much better suited for client-side dependencies than npm (as it makes a flat dependency tree), and seems to be more popular for newer packages. I'd propose something like the following workflow:
- user runs `npm install`
- npm installs Bower
- as a post-install task, npm runs our Grunt script
- Grunt calls Bower (via the Grunt plugin for Bower), to install all Bower dependencies
- Grunt scans all plugins directories, installing any Bower dependencies there too
- Grunt copies necessary files from dependencies to our build tree, possibly minifying them

This should also help to resolve some of the issues raised in https://github.com/girder/girder/issues/899 .

**Comment by jbeezley** [comment]
That's roughly what I did in GeoJS a while back, and I'm not sure it was a good idea.  From my experience:
* Many packages don't exist in bower so you end up using npm anyway.
* Since 3.0, npm makes a flat dependency tree as well; however, the way npm/bower manages dependencies isn't really relevant here because we are [bundling](https://github.com/girder/girder/blob/master/Gruntfile.js#L255) them together manually anyway.  If we used something like browserify, then this could be important.
* Using the postinstall hook is [fraught with problems](https://github.com/npm/npm/issues/1341) (the [npm docs](https://docs.npmjs.com/misc/scripts#best-practices) explicitly advise against it).

Because girder is an application rather than a client-side library, I don't think it is particularly important to make it available on bower either.  My vote would be to stay with npm.

**Comment by zachmullen** [comment]
> Using the postinstall hook is fraught with problems (the npm docs explicitly advise against it).

Hm, we do that to run our build process. Do you think we should not do that? I've noticed it's problematic on environments where girder is installed as root, since npm explicitly tries to run those tasks with lower privileges for whatever reason.

**Comment by jbeezley** [comment]
> Do you think we should not do that?

Probably, yes.  But because, girder isn't really a library, it is less important.  The issue is that when a package is installed as a dependency, it's dependencies won't necessarily show up in it's own `node_modules` directory.   If what you put in the post install hook relies on having any of those dependencies, it will fail.  This is the reason behind [this hackery](https://github.com/Kitware/minerva/pull/167).  Also if you follow the guidelines of using the prepublish hook to build, then all of the build time dependencies can go in `devDependencies`.

**Comment by brianhelba** [comment]
> we use that hook to run our build process

That's just why I mentioned using the post-install operation. @jbeezley , if you have a better way to kick off the Grunt process from npm, it should totally safe to change ``package.json`` to use that instead.

For better or worse, I think we're stuck with supporting ``npm install`` as the way to bootstrap Girder, both because we need to use npm to install Bower, and because all of our installation documentation references ``npm install``.

**Comment by jbeezley** [comment]
See [here](https://github.com/npm/npm/issues/3059#issuecomment-12282746) from the main developer: 

> Eventually, arbitrary pre/post/install scripts will be removed, and node-gyp will be the only thing that will be run at install time. Compilation of binary addons is the only justifiable use of install-time scripts.

The recommended method is to use a custom install script, like this:
```json
{
  "scripts": {
    "dobuild": "grunt init default"
  }
}
```
Then
```bash
npm run dobuild
```

That way `npm install` won't fail if others try to use girder as a dependency (should that ever happen).  That is why I made [this change](https://github.com/OpenGeoscience/geojs/pull/461) to GeoJS.

**Comment by brianhelba** [comment]
That seems reasonable; I don't know enough about npm to comment beyond that.

Is this something that we can change right now? Do you want to make a PR to update ``package.json`` in Girder, @jbeezley ?

**Comment by jbeezley** [comment]
I wouldn't consider it hugely important.  The main issue is that it will effect people's workflows (i.e.  `npm install && npm run build`) and the documentation.  I can prepare a PR later today or tomorrow.

**Comment by brianhelba** [comment]
Now that we're building things on the server-side with Webpack, Bower makes much less sense. Closing.
