### ISSUE TITLE
PUT /system/check does not recompute sizes for top level entities

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1321]

**Comment by manthey** [comment]
My original intent was that each model would have a `checkConsistency` method that has three stages: `count` returns the number of that type of model, `remove` removes orphaned instances of the model, and `verify` checks and corrects instances of the model, including size.  This will probably need to be added for `folder`, `user`, and `collection` models.  Currently, there is a list of models that gets checked (https://github.com/girder/girder/blob/master/girder/api/v1/system.py#L352).  Rather than maintaining such a list, it would be better to run the check on all models that have such a method.
