### ISSUE TITLE
Allow fetching of total number of items for paging widgets

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1603]

**Comment by opadron** [comment]
@zachmullen I wonder how to do this when filtering client-side.  Should we unconditionally return the total number of records, without considering client-defined filters?  If we want to take those filters into account, it would seem like we'd just have to iterate over all records and process them on the client.  Would this course of action not defeat the purpose of paging?

HTH

**Comment by manthey** [comment]
I'd like to eventually address this issue (also https://github.com/DigitalSlideArchive/HistomicsTK/issues/173).

This could be done by adding appropriate headers (a la PR #2105), but the perennial problem is that we have to enumerate all resources and filter them by permissions in order to determine how many of them are available to the user that is making the request.

Girder allows access if:
- The user is an admin
- The resource is marked public
- The user is in the resource’s access.users list with at least the access level specified
- One of the user’s groups is in the resource’s access.groups list with at least the access level specified
Access is further restricted if an access flag is specified and the flag is not set on that resource for the user/group access level.

I propose adding a `findWithPermissions` method to ACL models and to models using the ACL mixin.  The below method could be used in place of `model.find` on queries WITHOUT access flags, and returns a mongo cursor.  This cursor is a standard cursor, so `count()` can be executed on it.
```
    def findWithPermissions(self, query=None, offset=0, limit=0, timeout=None, fields=None, sort=None, user=None, level=AccessType.READ, **kwargs):
        # An appropriate doc string goes here 
        # if you make level explicitly None, this skips permission checks

        # If no user is specified and greater than READ access is requested,
        # we won't return anything.  So as to always return a cursor for
        # consistency, we make a query that will return no results
        if user is None and level is not None and level > AccessType.READ:
            query = {'__matchnothing': 'nothing'}
        elif level is not None and (not user or not user['admin']):
            query = query or {}
            permissionClauses = [
                {'public': True},
            ]
            if user:
                permissionClauses.extend([
                    {'access.users': {'$elemMatch': {
                        'id': user['_id'],
                        'level': {'$gte': level}}}},
                    {'access.groups': {'$elemMatch': {
                        'id': {'$in': user.get('groups', [])},
                        'level': {'$gte': level}}}},
                ])
            if getattr(self, 'resourceColl', None) and getattr(self, 'resourceParent', None):
                # Get the set of possible resource parent IDs.
                allParentIds = [
                    entry['_id'] for entry in self.collection.aggregate([
                        {'$match': query},
                        {'$group': {'_id': '$' + self.resourceParent}},
                    ])]
                # Filter it to parents we can access
                parentIds = [entry['_id'] for entry in
                             self.model(self.resourceColl).collection.find({
                                 '_id': {'$in': allParentIds},
                                 '$or': permissionClauses
                             })]
                query = {'$and': [query, {self.resourceParent: {'$in': parentIds}}]}
            else:
                query = {'$and': [query, {'$or': permissionClauses}]}
        return self.find(query, offset, limit, timeout, fields, sort, **kwargs)
```
For ACL models, this just augments the query with the necessary permission clauses, so that `filterResultsByPermission` is not required.

For ACL-mixin models, this ends up performing TWO queries: the first does an aggregation to get the set of the ACL resource ids that exist in the query AND have the necessary permissions.  The second performs the original query filtered to only those elements that are controlled by a resource returned by the first query.  For large databases where most entries will have the correct permissions, this is certainly going to have a time cost.  However, the number of expected entries can now be known.

**Why this can’t be done with a single aggregation:**

This looks like it would be a candidate for (using an item model as an example with some pseudocode):
```
  collection.aggregate([
    {$match: <<query>>},
    {$lookup: {from: 'folder', localField: 'folderId', foreignField: '_id', as: '_access'}},
    {$match: {$or: [
      {_access.public: true}, 
      {'_.access.access.users': {$elemMatch: {
        id: user[‘_id’], 
        level: {$gte: <<level>>}}
      }}, 
      {'_access.access.groups': {$elemMatch: {
        id: {$in: user.get(‘groups’, [])}, 
        level: {$gte: <<level>>}}
      }},
    ]}},
    {$project: {_access: false}}
  ])
```
However, the `$lookup` aggregation pipeline step *does not work* on sharded collections, so this would break sharding support in Girder.

Also, trying this out reveals that we expect a python iterator as a return value from certain functions (`childFolders`, for instance) and NOT a mongo cursor (which is iterable but not an iterator).  With a mongo cursor `cursor.next()` works, but `next(cursor)` does not (or `six.next(cursor)`); you have to use `next(iter(cursor))`.

**Comment by manthey** [comment]
We could allow endpoints to return a mongo cursor instead of a list.  This would get a header (`X-Total-Count`, perhaps) set to `cursor.count()` and then the cursor would get cast to a list as part of `filtermodel` or `endpointDecorator`.

**Comment by brianhelba** [comment]
> For ACL-mixin models, this ends up performing TWO queries: the first does an aggregation to get the set of the ACL resource ids that exist in the query AND have the necessary permissions. The second performs the original query filtered to only those elements that are controlled by a resource returned by the first query. For large databases where most entries will have the correct permissions, this is certainly going to have a time cost. However, the number of expected entries can now be known.

For large databases, I'm not sure if this would scale at all. Passing thousands of elements to `$in` is going to break MongoDB at some point.

Your point about `$lookup` (a.k.a. the `JOIN` operator) not working on sharding is to me a reason to consider dropping support for allowing access-controlled models to be sharded. We're likely going to hit the scaling limits of using `$in` well before we hit a limit where sharding is necessary. Aggregation pipelines (definitely including `$lookup` / `JOIN`) are critical to scaling MongoDB in any real way, so at this point, I'd call sharding of access-controlled models a breaking premature optimization.

Otherwise you have my +1 of support to the goal of this effort / a `findWithPermissions` method.

**Comment by manthey** [comment]
@brianhelba, @zachmullen  I pushed a WIP branch called `find-with-permissions`.  I'd love to hear some feedback on it before I bother expanding tests and turning it into a PR.

**Comment by brianhelba** [comment]
Could you make it a WIP PR? It's sometimes easier to review and discuss that way.

**Comment by manthey** [comment]
PR #2614.
