### ISSUE TITLE
Refresh causes re-notification of past events

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#1866]
@manthey mentioned this in the gitter channel last week:
> When I switch away from a Girder tab in a browser and switch back, I get renotified of various events. This is probably due to PR #1687 which detaches the event stream. It would be nice if it remembered what had been shown so as to not reshow messages 

I just recently encountered the same behavior.

**Comment by jbeezley** [comment]
I'm considering working on this because it has been annoying me lately, but I could use some input on how we want to solve it.  Looking at the notification code, there are a few problems that need to be solved.

1. When a notification stream is created, all notification documents are always returned even if it is just recreating a timed out stream.
2. There is [some code](https://github.com/girder/girder/blob/master/girder/api/v1/notification.py#L78-L79) that looks like it is trying to filter notifications after a timestamp, but it isn't actually doing anything because `lastUpdate` is always `None` when the function is called.
3. Jobs always use the default notification expiration of 1 hour, so opening the page, reloading, or backgrounding the tab will always result in sending all job notifications from the last 1 hour.

In terms of solutions, I'm thinking of one or more of the following to solve these problems:

1. Add an optional parameter to `GET /notification/stream` to filter out notifications before a given timestamp.  This would allow the client to avoid getting notifications that have already been shown in the current session when restarting the event stream.
2. Reduce the default notification expiration time (5 minutes?).
3. Limit the number of notifications shown when starting up an event stream to a small number (3?).  This could also be a an optional parameter in `GET /notification/stream`.
4. Give the user an easy way to dismiss all incoming notifications when too many are coming in at once.

I'm curious if anyone has opinions about these options, or perhaps has any other ideas.

**Comment by zachmullen** [comment]
The reason my initial design for this started with an empty timestamp was to avoid clock synchronization between client and server, always using the server time as the authoritative clock. One solution would be to just store this last updated stamp in a cookie. It's been a while since I've looked at the code, though, so I'm not sure if that by itself would be sufficient.

**Comment by mgrauer** [comment]
@jbeezley I'm on board with your proposed changes generally, but the one I like the most is 

>4. Give the user an easy way to dismiss all incoming notifications when too many are coming in at once.

At least with that, no matter what is going on with defaults or re-notification, or however else we try to solve the problem, the user can ignore them and move on.

**Comment by manthey** [comment]
I like option 1.

If the client keeps the last timestamp of any notification it receives and passes that timestamp to the endpoint when asking for new notifications, then, provided the server has monotonic time, it will only get new events.

I find the extra notifications intrusive when switching back and forth between tabs, and the client could store that timestamp just in javscript to resolve that issue (only sending it when resuming a notification stream).  If we use a cookie, then it would also prevent seeing the notifications if you reload the web page.

**Comment by jbeezley** [comment]
The clock synchronization issue could be a real problem.  I think setting a cookie from the server is the best option.

**Comment by zachmullen** [comment]
If we add more cookie utilities, I vote for moving the [cookie utils](https://doc.esdoc.org/github.com/girder/girder/variable/index.html#static-variable-cookie) into their own module under utilities/cookie.js so we can document them more easily.
