### ISSUE TITLE
Plugin deps fail to install with npm v5

### ISSUE THREAD

**Issue by jbeezley** [girder/girder#2045]
I saw this when submitting #2043, but it took me a while to validate what was going on.  This seems to apply only to npm v5 and only on the invocation of `girder-install web --all-plugins`.  The output from the initial install is [here](https://gist.github.com/jbeezley/d40fc53421cbb05852c3c788533ef85e).  After running, the dependencies (vega in this case) are not installed in `node_modules`.  Here, the failure is in the jobs plugin, but similar behavior appears for any plugin installing extra dependencies.

What is weird is that I have found that you can run `girder-install web --plugins jobs` to fix the error building the jobs plugin.  After that, running with `--all-plugins` will fail on the ldap plugin due to the missing sortablejs.  And again, you can fix it by building that plugin alone.  To get, `--all-plugins` to succeed, you have to first install each plugin individually.

**Comment by brianhelba** [comment]
I assume this is referring to NodeJS v5, since [npm's latest version is 4.6.1](https://www.npmjs.com/package/npm).

Node.js 5.x is past EOL, with [support dropped in June 2016](https://github.com/nodejs/LTS). Unless this issue also applies to Node 4.x or 6.x, I'd propose updating the test environment to use a supported Node version, then make it clear in https://github.com/girder/girder/issues/1848 that Node 5.x should not be used.

**Comment by jbeezley** [comment]
No, it's about npm http://blog.npmjs.org/post/161081169345/v500

**Comment by jbeezley** [comment]
To follow up on this, it appears that the new behavior of `npm install` is to first prune `node_modules` and then perform the install.

```
$ npm install --no-save sortablejs
added 1 package in 2.908s

$ ls -ld node_modules/sortablejs node_modules/geojs
ls: cannot access 'node_modules/geojs': No such file or directory
drwxrwxr-x 2 jbeezley jbeezley 4096 May 31 10:45 node_modules/sortablejs

$ npm install --no-save geojs
added 3 packages and removed 1 package in 3.087s

$ ls -ld node_modules/sortablejs node_modules/geojs
ls: cannot access 'node_modules/sortablejs': No such file or directory
drwxrwxr-x 7 jbeezley jbeezley 4096 May 31 10:45 node_modules/geojs
```

I'm searching for a workaround, but if I can't find one we will have to change how we install plugin dependencies.  This should be a high priority to fix because as of this morning npm@5 is marked as the latest version on npm, so anyone who updates it will hit this bug.

**Comment by zachmullen** [comment]
Is there no command line flag to disable the prune behavior?

**Comment by zachmullen** [comment]
The docs say we should commit the lock file, but I'm guessing we can't do that since the state of our node_modules depend on plugins

**Comment by jbeezley** [comment]
Yes, exactly.

**Comment by zachmullen** [comment]
If we add `--no-save` to the npm install command in install.py, it does not create a package-lock.json file at all, but the problem still persists, so I don't think this is a result of the lock file state.

**Comment by zachmullen** [comment]
My current understanding of the problem: if you run `npm install --no-save some_package`, npm5 attempts to prune the final tree down such that the state is the union of some_package's tree and the tree defined by the package.json file in the directory. The problem happens because we run multiple consecutive npm install commands for specific packages, one per plugin that has npm deps.

A possible solution would be to combine all of the npm install steps for the plugins being installed into a single npm install command.

**Comment by jbeezley** [comment]
That is the solution I was considering as well.  It would have the added benefit of making the install process significantly faster.

**Comment by zachmullen** [comment]
Sounds good to me, do you have time to implement it?

**Comment by jbeezley** [comment]
I'll try to get something in soon.
