### ISSUE TITLE
Girder web core can't be built without access to Mongo

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#2089]
Our client side code can't be built without access to a mongo database unless passing the `--all-plugins` flag or explicitly specifying the enabled plugins with `--plugins=x,y,z`. Sometimes it's desirable to perform the web build with no additional plugins or access to a mongo database, a workaround is to run `girder-install web --plugins=,` and ignore the warning message.

**Comment by zachmullen** [comment]
I consider it a bug that `--plugins=` doesn't work, and even better would be an explicit `--core-only` option that does the same thing.

**Comment by brianhelba** [comment]
What's the use case for building the client without access to MongoDB? I don't know if this is a case we actually want to commit to supporting, as I could see DB access being necessary for more sophisticated client-side build-time features. (For instance, there are several benefits to having Webpack build the root HTML file too, rather than it being a Python template. In this case, we'd need API root info, perhaps some version info, etc. available at build time. Some of this could come from a config file, but I wouldn't want to commit to this.)

+1 for a sane way to force-build only the core though.

**Comment by manthey** [comment]
At the very least, building without a MongoDB is useful for making Docker images that can be deployed and updated against a database external to Docker.

**Comment by brianhelba** [comment]
Ok, maybe this is overkill, but would it make sense for our web client build system to use the HTTP API to get any and all information that it needs (enabled plugins right now, other stuff in the future). This has the benefit of removing a point of backdoor database access in the web build system. It also potentially allows more flexible build environments, as it should be easier and more reasonable to expose a public HTTP port to a Docker (or similar) environment, rather than a localhost-only-bound MongoDB port.

**Comment by manthey** [comment]
When Girder is running, we *require* access to a Mongo database.  This is trying to allow building a certain way when Girder is *not* running, and *cannot* run because no database is present.  We use Girder's settings model during the install when we want to query a setting.  This accesses the Mongo database as Girder (the database may or may not be local).

**Comment by brianhelba** [comment]
I understand how the build process connects now. My idea (perhaps a bad one) would indeed require an instance of girder-server to be running (which is strictly a greater requirement than just MongoDB) during build-time, in exchange for perhaps some theoretically greater decoupling between the server layers and the client build process.

I am, however, admittedly not totally clear on what the issue is when building a Docker environment. Is it not possible to spin up and connect a temporary MongoDB instance (or in my proposal, a server instance) to the Docker build process?

Finally, note that I still agree that you should be able to build core-only (or really any CLI-specified list of plugins) in a sane way right now without having to connect to the DB. I'm just hesitant to commit to always supporting some way for the build process to run without a DB / server, if we later want to add more advanced build features.

**Comment by brianhelba** [comment]
Also, binding MongoDB to non-localhost network interfaces is pretty scary, given how bad it's connection-level security is (without extensive configuration and re-compilation). I'm not sure if there is some build environment that would need to connect to a non-local DB, but that could be another reason to connect via HTTP instead (again, in the cases where we would *need* to connect).

**Comment by manthey** [comment]
Again, with the Docker example: I deploy using a set of docker containers.  1 for Mongo (with the db stored on the local file system, not the docker file system), 1 for Girder, 1 for girder_worker, 1 for RabbitMQ.  These share a docker network, but the mongodb appears "not local" to the Girder docker container, even though it is in an isolated internal network.

Why spin up a database during a build process?  Currently I don't need Mongo deployed on the environment building Girder (such as docker-hub).  Also, it is time-consuming and won't have the same values as the actual deployed environment.  I've built all plugins in a docker image so that, when deployed, I don't have to rebuild the client-side code at all.  The actual deployment could have any subset of available plugins and still work.  I can see the use case where no plugins are need or wanted, too; you end up with a substantially smaller deployment.

**Comment by kotfic** [comment]
In general it would be my preference for building girder to rely on ***no*** external services. While it might not be operationally that different to rely on girder's API instead of a running mongo database, it feels like its doubling down on a solution that i'm already unhappy with.

**Comment by danlamanna** [comment]
> Ok, maybe this is overkill, but would it make sense for our web client build system to use the HTTP API to get any and all information that it needs (enabled plugins right now, other stuff in the future)? 

IMHO, this is overkill *and* premature optimization. There's a distinct code smell with the notion that building javascript should require a database connection to begin with. This is an auto-detection feature that has made me wish it were opt in more than once. Maybe @jbeezley can chime in, based on his packaging discussion on Friday it seems like this requirement may be removed eventually anyway.

**Comment by zachmullen** [comment]
To clarify, building our web client does not require a mongodb connection. A mongodb connection is only used in the default no-argument case; prior to this behavior, Girder always built every plugin, but that was becoming untenable due to the number of builtin plugins, and so this was judged to be the most intuitive behavior in the default case: to build only the enabled plugins. Discovering the enabled plugins *does* require a mongo lookup.

If people are unhappy with that default case, we can change it in 3.0. However, in the mean time, there is a legitimate bug / missing important feature here, which is the inability to build just core with no plugins. That fix is actually quite simple.

**Comment by jbeezley** [comment]
Requiring external services to be present for building is definitely unusual in the javascript world.  I think a more sane default would be to build all plugins because the plugin bundles are all independent and won't be served. It may be useful to provide an option to connect to an API server to determine build configuration, but I don't see an immediate need for it.

My vote would be to do the following:
1. default to building all plugins
2. add a `--no-plugins` option
3. add autodiscovery of dependent plugins when providing a list of plugins (`--plugins item_tasks` would enable `worker` and `jobs` automatically)
4. consider adding something like `-api-root` for autoconfiguration in the future

1-3 would not require any external services.  4 would provide decoupling between the client and the database.

**Comment by zachmullen** [comment]
> Requiring external services to be present for building is definitely unusual in the javascript world. 

So is building javascript via a python entrypoint :)

We do have npm scripts that also do this, and none of them connect to mongodb.

**Comment by jbeezley** [comment]
> So is building javascript via a python entrypoint :)

I don't think it's all that unusual for projects that have a python web server.  It's how JupyterLab and Jupyter Notebook work.

**Comment by zachmullen** [comment]
If the eventual goal is to decouple our packaging of javascript and python, would you even keep this entrypoint around?

**Comment by kotfic** [comment]
While I like @jbeezley recommendations these seem like breaking changes (e.g. girder 3.0).  Please also note that @sutartmelson has assigned himself to this task on Friday. I believe he is planning on implementing the ```--core-only``` option which at least for the foreseeable future is a non breaking change that addresses the original issue.

**Comment by zachmullen** [comment]
@jbeezley 3. on your list is already the way it works 😄

**Comment by brianhelba** [comment]
For the record, I spoke with @manthey about this further. At this point, I'd now generally support the direction that @jbeezley is proposing.

**Comment by jbeezley** [comment]
> If the eventual goal is to decouple our packaging of javascript and python, would you even keep this entrypoint around?

We would probably still want it.  Even if we a have pure "javascript way" of building, we still need to copy the built assets into the correct directory.  Assuming the static files are stored somewhere in the python prefix, you would need python to tell you the correct place.
