### ISSUE TITLE
Allow searching DICOM metadata

### ISSUE THREAD

**Issue by Pierre-Assemat** [girder/girder#2313]
For now, there was only two different search mode:
- `textSearch`
- `prefixSearch`

And we can't search inside metadata of file or item. For the DicomViewer plugin it will be interesting to be able to search inside tags/values using the search bar.

The question is : 

Does these changes are used enough to be a girder_core changes and allowed more generally new search mode or a way to search in all metadata ?
Or does these changes have to stay inside the Dicom plugin ? 

More details about the expectations : 
The search will start with any tag (key) that match to a value (or prefix) and return the item not the file.

**Comment by mgrauer** [comment]
The requirements I have are

 * search for metadata that is the same across the files of an item, and return an item, i.e. search for the study instead of the series
 * search by prefix (at least have this as a mode) of a value, in addition to the entire value
 * search for any tag matching a given value or prefix

I'd like to this via an extension to the standard search UI (mainly because I think it will be the lowest effort and because users won't have to learn a new search UI), potentially with some new search modes added in, e.g. a dropdown option for "Dicom metadata" and "Dicom metadata prefix".  I'd be ok with a custom search syntax, e.g. `my_key=my_value`, or for value only queries `value:my_value`.
