### ISSUE TITLE
Give item download links a better title

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#2326]
My thoughts here might be too PDF centric and focused around when viewing the file in the browser, as in this may not generalize well enough.

Could we give the download item link a better title, perhaps the item name?

See this [item download view](https://data.kitware.com/api/v1/item/59a05d2a8d777f7d33e9ccea/download?contentDisposition=inline) for example, the current title is "download", and it would be better as the item name or maybe a new `title` field.

**Comment by ronichoudhury** [comment]
I think this would make Girder a quantum friendlier.

I brought this up once before but there was some technical reason not to do it - I think because the endpoint you're hitting really is called `download`, and the web already provides ways to set the actual downloaded filename, even if that's different from the actual route name, etc.

**Comment by zachmullen** [comment]
I would say this is the PDF viewer misbehaving. Looking at the response, it's setting:

    Content-Disposition:inline; filename="CMF_2017.pdf"

But the PDF viewer does not honor that, and chooses instead to use the last path token. I'm OK with allowing an item download endpoint like we have for file download ones that just ignores the last path token, and having our web front-end use that for inline viewing.

**Comment by manthey** [comment]
This reminds me that we should be using a more complex form of `Content-Disposition` to handle unicode characters in the appropriate manner:
`Content-Disposition:inline; filename="safe_name.pdf"; filename*=UTF-8''quoted_unicode_name.pdf`

I think, given `filename`, what we probably should be doing is:
```
if not isinstance(filename, six.text_type):
    filename = filename.decode('utf8', 'ignore')
safeFilename = filename.encode('ascii', 'ignore').replace(b'"', b'')   # ascii is more restrictive than necessary
encodedFilename = six.moves.urllib.parse.quote(filename.encode('utf8', 'ignore'))
setResponseHeader('Content-Disposition', '%s; filename="%s"; filename*=UTF-8\'\'%s' % (
    contentDisposition, safeFilename, encodedFilename))
```

Otherwise, the specified filename doesn't work in some cases even for downloading (for example, a mixture of emoji and Cyrillic on my version of Chrome).

**Comment by mgrauer** [comment]
What's weird is that this works for some items.  I can't figure out the difference.

https://data.kitware.com/#item/59846cff8d777f7d33e9c079
https://data.kitware.com/#item/59a05d2a8d777f7d33e9ccea

Both of these are single file items, where the file name is the same as the item name, and with `"mimeType": "application/pdf"`.  One of them displays the name as the title of the pdf and the other displays "download".

The response headers also look very similar

    Content-Disposition:inline; filename="2008 Davis Thesis UNC.pdf"
    Content-Disposition:inline; filename="CMF_2017.pdf"

**Comment by manthey** [comment]
At least on my version of Chrome (60.0.3112.113), the first shows a title, but it isn't the Content-Disposition title, it is a `/Title()` record from inside the PDF ("Medical Image Analysis via Fréchet Means of
Diffeomorphisms", not "2008 Davis Thesis UNC.pdf").

If the url includes the filename as part of the path (e.g., `https://data.kitware.com/#item/59a05d2a8d777f7d33e9ccea/download/CMF_2017.pdf?contentDisposition=inline`), then Chrome's PDF viewer shows the filename but only IF the PDF doesn't specify a title.

**Comment by manthey** [comment]
This was done in PR #2330.
