### ISSUE TITLE
Add a new view for search results

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#2339]
To make it easier to browse a global search yielding multiple results, a new view should be added, which will show search results on a stable page, as opposed to a pop-over. This could be linked from the existing search results pop-over, or be navigated to when a user presses `Enter` in the search dialog.

**Comment by Pierre-Assemat** [comment]
I have some question about how the `SearchFieldWidget` should display the result. I'm not talking about the display of the new `searchResultView` but about how the dialog box which is shown after putting some query in the search field : 

For now the searchWidget is like this : 
![screenshot from 2017-09-14 12-46-26](https://user-images.githubusercontent.com/29961430/30442540-c009c5d0-994a-11e7-8eb5-7a5c37d63e0a.png)

There is two different possibilities : 
1) We can keep this, and add a last element at the end like this : 
![screenshot from 2017-09-14 12-48-39](https://user-images.githubusercontent.com/29961430/30442661-0ec8d760-994b-11e7-8a7d-d4b483a9d1f2.png)

But I think if we choose that, we need to limit the number of result displayed, like 3 or 5 at maximum.
The `...` element if it's selected go to the `SearchResults` page, and press 'Enter' too which could bring some minor issues with the old selection method (using 'arrow up', 'arrow down' to select the good result and 'Enter' to go to the selected result).

2) We can also stop showing this dialog box and just go to the  `SearchResults` page each time someone press 'Enter' after tipping some queries into the search field

Both of this possibilities bring some advantage and disadvantage, for example the first one is preferable when the number of results elements is low because of is rapidity but if there is too much search results isn't worth it...

What do you think about it @girder/developers ?

**Comment by opadron** [comment]
On point 1, I am in full agreement, @Pierre-Assemat.  I think limiting the number of previewed results and adding a "show me more" choice at the end is the right idea.

On point 2, I'm personally torn between having ENTER send me to the extended results page; and having ENTER send me to the top hit.

What about:
  - If user hits ENTER:
    - Send the user to the top hit if the entered query narrows the possibilities down to exactly one
    - Send the user to the extended results page if there is more than one choice
    - Do nothing (maybe add a small message) if the user types something that doesn't match anything

I wonder what other folks think!

**Comment by Pierre-Assemat** [comment]
I like the both... Maybe we could just do both in the same time : 
- limit the number of previewed results and adding  a "show me more" choice at the end
- allow to use ENTER following : 
    - Send the user to the top hit if the entered query narrows the possibilities down to exactly one
    - Send the user to the extended results page if there is more than one choice
    - Do nothing (maybe add a small message) if the user types something that doesn't match anything (and this is already done) 

Then how many is the number of previewed results ? I don't think it should be over 5 and under 3
![screenshot from 2017-09-14 13-22-43](https://user-images.githubusercontent.com/29961430/30444111-cfeee692-994f-11e7-9683-14a5cf36f7ba.png)

**Comment by opadron** [comment]
I would say 5, for frankly no objective reason, whatsoever!

In any case, it should be limited to a small number.  Six is clearly too many, imo. (Unless you're on your way to 10, then I'm not sure).

I feel like there's a Monty Python joke here, somewhere...

**Comment by zachmullen** [comment]
5? Feels a little anthropocentric, to me. #privilegecheck

**Comment by jeffbaumes** [comment]
https://drive.google.com has a reasonable behavior. ENTER always goes to the search results page (even if one or zero hits). Down arrow is required to select from the dropdown. Reasons for this approach: (1) The drop-down might not populate before the person presses ENTER and we shouldn't wait for that request to complete. (2) Muscle memory. Someone might type into a search box and hit enter without actively looking at the screen/search box, and expect to get a results page consistently, even if it is a "no results" page. 

I like the idea of an empty-result indicator on the drop-down so that it is always shown.

**Comment by zachmullen** [comment]
+1 for Jeff's suggestion, mostly because that's what Google search does.

**Comment by Pierre-Assemat** [comment]
I like even more this idea
Thank you all !

**Comment by Pierre-Assemat** [comment]
What do you think about this kind of views for the results @girder/developers : 
 - The results dialog box
![screenshot from 2017-09-14 23-51-06](https://user-images.githubusercontent.com/29961430/30465841-b1ed3fce-99a7-11e7-9f33-ed3acea2ba17.png)

- The results page with results
![screenshot from 2017-09-14 23-51-35](https://user-images.githubusercontent.com/29961430/30465846-b591bd12-99a7-11e7-807b-02f0bd3abd89.png)

- The results page without results
![screenshot from 2017-09-14 23-50-40](https://user-images.githubusercontent.com/29961430/30465845-b4806f9a-99a7-11e7-8504-f308fefe0a9b.png)

There is only one thing that bother me with this kind of display is if there are two elements with the same name but in two different place, without other information it could be an issue, maybe we need do show the hierarchy or at least the first parent if it exist.

**Comment by jeffbaumes** [comment]
Something like this would be a fine first shot, but I also have some thoughts if it's not too hard to make some of these changes:

* I think it should remain a flat list like the popup with an icon for each item. It would be more compact, plus it seems that pagination would be easier if things were collected into a single list.
* Order is also something to consider. Whatever we choose, we should try to keep the order the same in the popup and search results. My intuition tells me it should start with things that are likely to be "larger" concepts with fewer results, then move to "smaller" things. So I'd recommend the order of collection, user, folder, item. Custom search plugins could default to the top of the list, but perhaps should be able to be customized to appear in various slots. Ideally there would be a notion of "relevance" where a better item match could appear before a folder, but that seems overkill for now and would require a deeper discussion about relevance measures.
* The search text should remain after the user presses ENTER. It should serve as the natural header for the search results. It should be cleared when the user navigates away from the search results page.
* Just saying "Results" is fine instead of using "(s)" - seems ok to me for this to be the header even if there is just one item.

**Comment by Pierre-Assemat** [comment]
We have two different solution to the issue : 

- First : keep going in the display I propose, and try to add a sort of pagination per each different type
like this below (it just to show the idea) : 

![screenshot from 2017-09-20 13-54-25](https://user-images.githubusercontent.com/29961430/30659257-48f0fca0-9e0b-11e7-9e25-5433477ef4d7.png)
Where the search is done for each type, and results are independent as the `paginateWidget` too. In this case we don't need to change the behavior of the limit of pagination

- Second :   Do like @jeffbaumes propose, the same way that the `searchFieldWidget` display results with a flat list of result and an icon per element : 

![screenshot from 2017-09-20 14-04-12](https://user-images.githubusercontent.com/29961430/30659710-a69b9cec-9e0c-11e7-945e-c09c67325028.png)
This case force us to change the behavior of the `paginateWidget` in order to allow pagination for a list of different types

I prefer the first one for aesthetic reason and I think it will be more efficient for a user.
What do you think about that ? @girder/developers

**Comment by opadron** [comment]
I actually like breaking down the results by type, so much so that I would suggest going the other way and adding small headers to the dropdown (i.e.: "collections", and then a bunch of collections as sub-entries; then "users" and so on).

And keep the overall idea on the search page as it is, but I think you should deemphasize the headers -- they take up more space than necessary, imo.

**Comment by Pierre-Assemat** [comment]
I will try to implement @opadron idea and post some screenshot to show you

**Comment by Pierre-Assemat** [comment]
Something like this could be a first approach if we choose to display results by their types, and then we could choose to limit the number of element display not in total but maybe 2 or 3 per type

Here results are limited by 2 per type : 

![screenshot from 2017-09-25 13-03-30](https://user-images.githubusercontent.com/29961430/30821064-fb2ce746-a1f1-11e7-8c8d-441ebad623a1.png)

Here by 3 : 

![screenshot from 2017-09-25 13-08-53](https://user-images.githubusercontent.com/29961430/30821276-c3cd3160-a1f2-11e7-97ab-b6efde389127.png)

What do you think @girder/developers ?

**Comment by jeffbaumes** [comment]
With two in favor of grouping and one (me) in favor of a flat list, I'm good with going with grouping for now.

**Comment by zachmullen** [comment]
My vote is also for the flat list.

**Comment by jeffbaumes** [comment]
@girder/developers any other insight here? Google Drive, Dropbox also utilize ungrouped lists.

**Comment by danlamanna** [comment]
I prefer the ungrouped list as long as there are informative icons.

**Comment by Pierre-Assemat** [comment]
Go on the flat list for the search result dialog box then ! But for the sake of consistency, do you think we want a flat list on the result page (body) too ?

I'm not sure is the right approach for display a big amount of different type of resources, plus we will need to change the way the pagination widget works to use it in this case, but I think we also need to be consistent and avoid too much different display around search results

**Comment by zachmullen** [comment]
I'm fine with showing the category headers for the result page since we have way more space to work with there, and using the icons on that page could help people better grok their use in the small dropdown on subsequent uses.

**Comment by brianhelba** [comment]
@jeffbaumes @opadron @danlamanna @zachmullen @girder/developers 

@Pierre-Assemat [already brought this up](https://github.com/girder/girder/issues/2339#issuecomment-329674649), but I wanted to clarify the fact that with the current behavior of the `resource/search` endpoint, we *need* to group the results page by resource type, as it's the only sane way to handle pagination.

This is because the `limit` and `offset` parameters to `resource/search` are applied *independently* to each of the resource types. Thus, for a query like:
```
resource/search?types=["collection","folder","item"]&limit=3&offset=0
```
we could get results like:
```
{
    'collection': [
        {<collection doc 1>},
        {<collection doc 2>},
        {<collection doc 3>},
    ],
    'folder': [
        {<collection doc 1>},
        {<collection doc 2>},
    ],
    'item': [
    ],
}
```
When this query was re-run for the next page:
```
resource/search?types=["collection","folder","item"]&limit=3&offset=3
```
we could get results like:
```
{
    'collection': [
        {<collection doc 4>},
        {<collection doc 5>},
    ],
    'folder': [
    ],
    'item': [
    ],
}
```
The fact that the API works this way makes it sub-optimal to have a single set of pagination buttons on the search results page, as (using the above example), trying to see the next page of collections causes you to lose visibility on all of the folders (which has no next page).

The solution here is for each of the resource type groups to have their own pagination buttons, which would each request the next page of results for just that resource type. For example:
```
resource/search?types=["collection"]&limit=3&offset=3
```
---
An alternative would be to change the (currently ill-defined) behavior of `limit` and `offset` in `resource/search` to instead return `limit` resources *in total*, rather than per resource type. This would have several implications:
* It would make it easier to keep the search results mini-dropdown a reasonable size.
  * Currently, if we specify a `limit=3`, we actually get a maximum of 15 results, since the limit applies to each of `["item","folder","group","collection","user"]`. Girder actually currently uses a default limit of 10, so we get a maximum of 50 results in the dropdown.
  * With the change, we'd be able to say something like `limit=6` and get only 6 results total.
* It would allow global pagination of the search results page.
* It would require the server to decide on some sort of deterministic ordering mechanism for search results.
  * To start, we could just use a rule like: prefer an order of collections, groups, users, folders, items, then sort each alphabetically.
  * In the future, if the server was able to come up with some "relevance score" (perhaps based on the goodness of fit of the query, or based on the popularity of the result), it could use this to order search results, while abstracting this complexity from the client.
---
I don't have a personal opinion on this, but I wanted to make sure the situation was clear.

**Comment by Pierre-Assemat** [comment]
Thank you @brianhelba for this clarification

**Comment by jeffbaumes** [comment]
Yeah, I see the limitation now. +1 to the current approach that separates pagination for each type.
