### ISSUE TITLE
Assetstore generalization

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#2389]
Avoid using events system and “union” endpoint. I'm copying this from a document, I hope someone knows what "union" endpoint means.

**Comment by danlamanna** [comment]
The "union" endpoint refers to this endpoint:
https://github.com/girder/girder/blob/4e8d27a/girder/api/v1/assetstore.py#L104
(as well as updateAssetstore).

The issue is that the endpoints have to contain the superset of options for
all assetstores. One option @zachmullen suggested was deprecating that
endpoint and creating individual endpoints for each registered assetstore.

**Comment by brianhelba** [comment]
Please check out the comments in [this PR](https://github.com/girder/girder/pull/2309). There are some fundamental issues with the assetstore API that are ripe for improvement, particularly on the topic of using streams vs bytes objects and in terms of API consistency.

**Comment by mgrauer** [comment]
Next Steps: transform this into more concrete issues or else have a Girder planning discussion if anyone cares enough.

**Comment by jeffbaumes** [comment]
@girder/developers Someone who cares please take up this issue for discussion here or at the Girder planning meeting, or it may need to be removed from the 3.0 milestone.

**Comment by zachmullen** [comment]
I'm happy to do the work for this, and I think it's important to get into Girder 3.

**Comment by jeffbaumes** [comment]
Thanks @zachmullen

**Comment by manthey** [comment]
Outdated.
