### ISSUE TITLE
Remove girder-client functions concerned with performing http requests

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#2392]
This means instead of exposing functions for sendRestRequest, get, put, post, etc., we would simply expose a requests session object which would automatically append authentication headers once authenticated. This will allow for users to use the requests API for performing requests rather than ours.

**Comment by danlamanna** [comment]
I would like for this to involve removing sendRestRequest entirely. Is
that something we can do, does it require adding a deprecation tag now?

**Comment by jeffbaumes** [comment]
Up for discussion: Would anyone argue for keeping sendRestRequest in a deprecated state for a major release cycle? Or is our user base small enough to that the downsides of removing it are outweighed by the maintainability / code cleanliness of removing things outright in major releases as long as the fix is easily discoverable (e.g. in the 2->3 migration guide)? I'd argue slightly in favor of the latter.

**Comment by mgrauer** [comment]
We are closing this, the changes would be better suited to a complete restart of the Girder Python client/CLI.
