### ISSUE TITLE
Use yarn for web client install, at least for CI

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#2648]
In 2.x, this could just be maintaining a yarn.lock alongside our package-lock.json and allowing clients to use either yarn or npm. We would switch our CircleCI builds to use yarn and deprecate npm, and make an announcement on discourse that we plan to drop support for npm in a future major release.

**Comment by waxlamp** [comment]
Does anyone have specific experience in switching from npm to yarn? I'm curious about (1) what the realized benefits are and (2) any pain points in making the switch.

**Comment by zachmullen** [comment]
I did on girder-vue, it was extremely simple, but doing it in Girder could be significantly more difficult since we do weird stuff with plugin dependency installation. For that reason it might be better to wait until 3.0 to even try this.

**Comment by brianhelba** [comment]
I do not believe this is possible at all until Girder 3. The current system of using Grunt to `npm install plugin_dep_1 plugin_dep_2 ...` has no analog in `yarn` by design. Yarn only installs directly from a `package.json` file (which #2552 creates dynamically), and will not install one-off packages directly to a project. See #1743 for more info, but IMO, this is all for the best, as Girder's current behavior is actually a major source of slowness in the web client build process.

In Girder 3, if we do things correctly, the client build code ought to support both `npm` and `yarn` equally well, though we may one to decide on officially choosing one for the purposes of lockfiles and CI (and I'd probably vote `yarn`). Otherwise, the commands `npm install` / `yarn install` or `npm run build` / `yarn run build` should both work on the `package.json` that Girder generates.

**Comment by mgrauer** [comment]
Vue-Mooted.
