### ISSUE TITLE
Upgrade TableView plugin's version of datalib

### ISSUE THREAD

**Issue by waxlamp** [girder/girder#2727]
See [this comment](https://github.com/girder/girder/pull/2715#issuecomment-391711416).

**Comment by manthey** [comment]
It looks like **datalib** is being eschewed in favor of **vega-loader**.  The conversion from datalib to vega-loader is mostly straightforward, but vega-loader expects to have a `window.fetch` method, which doesn't exist in our PhantomJS testing environment.  I don't know if it exists in the latest version of PhantomJS, however adding polyfills (whatwg-fetch, for instance) allows it to work.  More generally, also adding a polyfill library like core-js allows the plugin to work on older browsers (e.g., IE 11).

A quick trial of converting to vega-loader works, except that the test for a bad data file fails because it is parsed (not well, but without errors).
