### ISSUE TITLE
Girder doesn't work behind a subpath reverse proxy

### ISSUE THREAD

**Issue by matthewma7** [girder/girder#2982]
The girder web client and the API page was using relative paths like these
```html
<script src="static/built/girder_lib.min.js"></script>
<script src="../static/built/swagger/swagger-ui.min.js"></script>
```
It worked when being put under a subpath by a reverse proxy.
such as http://localhost/subpath/

However, the latest master, uses absolute path
```html
<script src="/static/built/girder_lib.min.js"></script>
<script src="/static/built/swagger/swagger-ui.min.js"></script>
```
It doesn't work behind reverse proxy. becuase the the resource doesn't exists at `http://localhost/static/built/girder_lib.min.js` 
It actually exist at 
`http://localhost/subpath/static/built/girder_lib.min.js`
(Font and the API page still won't work even if I remove the leading slash by monkey patching)

Setting core.route_table like these doesn't help 
```json
[{"key":"core.route_table","value":{"core_girder":"/","core_static_root":"/subpath/static"}}]
```
Becuase even ouptut changed to
```html
<script src="/subpath/static/built/girder_lib.min.js"></script>
```
the resource now actually exists at
`http://localhost/subpath/subpath/static/built/girder_lib.min.js`

I didn't pinpoint which commits changed the behavior, it might be caused by a few commits.
But girder at this hash works. 7327d0039d760114a09aafd6d102b89561144f63
The reverse proxy I was using is a node application, the test script is [here](https://gist.github.com/matthewma7/052c994f09fa11768af07f5424aad07e).

**Comment by brianhelba** [comment]
I understand the issue.

There are 2 path prefixes here, which I'll designate `staticRoot` and `publicPath`. `staticRoot` is where CherryPy serves static content. `publicPath` is where that static content can be fetched by end user agents. The problem is that the Girder setting `STATIC_ROOT` conflates these two different prefixes.

I'm going to boldly claim that nobody ever really wants to change `staticRoot`. Girder tries to support serving static content from a different location all by itself, but the best approach should actually be to just use a reverse proxy, as @matthewma7 is doing. I think the solution here is to apply parts of https://github.com/girder/girder/pull/2893 and hardcode CherryPy to always serve from `/static`.

For compatibility, we should keep the `STATIC_ROOT` setting, but make it behave purely as `publicPath`. It will simply affect how Mako templates and Webpack generate inline URLs to served content.

**Comment by brianhelba** [comment]
I'm working on a fix now.
