### ISSUE TITLE
Expose user details endpoint to log in users

### ISSUE THREAD

**Issue by matthewma7** [girder/girder#3008]
At this moment, [the `user/details` endpoint is limited to only admin users.](https://github.com/girder/girder/blob/master/girder/api/v1/user.py#L212)
But I don't see why since anonymous users were able to list all user.
(only logged-in user can list users now. https://github.com/girder/girder/pull/2978)

Expected result: Open the user details user open to any logged-in user. 

PS: This girder/girder_web_components#119 would use this.

**Comment by brianhelba** [comment]
The reason is that since `User` is an `AccessControlledModel`, it's non-trivial to count the total number of apparent users that a given non-admin requester is able to see.

However, since `user/details` was first added, we now have `findWithPermissions`. If you can use `User.findWithPermissions` to generate the counts, you should be able to allow non-admins to call the endpoint.

**Comment by brianhelba** [comment]
To clarify, typically, all users are `public=True` and therefore are all visible. However, plugins make it possible to have a `public=False` private user, so the `user/details` endpoint shouldn't dig us further into the assumption that all users are always public.

**Comment by matthewma7** [comment]
Thank you @brianhelba for explaining the background.
Ok, cool, I'll update the existing code to do so.
