### ISSUE TITLE
Combine with OpenSeadragon JavaScript

### ISSUE THREAD

**Issue by zzzghm** [girder/girder#3100]
I had an web-viewer based on OpenSeadragon, and I would like to combine the viewer with HistomicsTK and girder to better analysis and manage the whole slide images. I am wondering where can I find lower level code that you called the OpenSeadragon as a function that I can modify, in that case, I can start from there to combine our viewer with Girder. Thank you!

**Comment by manthey** [comment]
The large_image plugin has an OpenSeadragon viewer that is used in the Girder client: https://github.com/girder/large_image/blob/master/web_client/views/imageViewerWidget/openseadragon.js 
If you want to combine the OSD viewer with annotations or other overlays, I would also have a GeoJS layer for the annotations and then have code to synchronize the OSD and GeoJS zoom and positions.

I'll close this issue here, since the topic is more relevant to large_image than to Girder.
