### ISSUE TITLE
What python version will this run Girder as?

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#3131]
Issue meta-issue: Issues were not enabled on this repo. I had to enable them before I could create this one. Perhaps that will open the floodgate.

My real issue is what Python version will this run Girder as? It seems like from [here](https://github.com/girder/ansible-role-girder/blob/master/tasks/main.yml#L22-L32) it will run as whatever is the system Python3.

Is there a way this would not be true? If you pass in your own value for `girder_virtualenv`?

I think my confusion stems from this comment in the readme for `girder_virtualenv`:

>Path to a Python virtual environment to install Girder in. Will be implicitly created if using Python 3.

Did this comment make more sense before there was a change to use system Python3 as a default? How should it be updated?

Overall I'd like to have the Readme clarify that system Python3 will be used as a default and have this comment be updated with whatever makes sense.

**Comment by brianhelba** [comment]
Regarding the meta-issue: the repository https://github.com/girder/ansible-role-girder is not the upstream home of the `girder.girder` Ansible role; that code properly lives at https://github.com/girder/girder/tree/master/devops/ansible-role-girder . The repo https://github.com/girder/ansible-role-girder is a read-only mirror to accommodate the fact that Ansible Galaxy can't pull roles unless they live at the top level of a dedicated repository; this repo should generally be ignored on GitHub. The `girder.girder` role metadata properly indicates that new issues should be filed under https://github.com/girder/girder/issues .

So, I've disabled the issues feature on https://github.com/girder/ansible-role-girder again, to keep things from fragmenting.

**Comment by brianhelba** [comment]
@mgrauer Regarding Python versions, were you asking about Python 2 vs 3, or about different version of Python 3 (e.g. 3.6 vs 3.7)?

Most of the role documentation was written around the primary concern of dealing with Python 2 vs Python 3, since both are commonly available on a system at the same time. I think we should update the docs to be more opinionated around encouraging people to just use Python 3 (although it will remain technically possible to use Python 2, just with more work offloaded to the user), which may further simplify things for the common case and prevent confusion.

Finally, note that part of the confusion may relate from the fact that there are two totally different contexts in which the Python version matters:
* The version of Python which we run Ansible under on the target machine
* The version of Python which Girder runs under

Things are much easier when both of these are the same version, so again, I'll update the docs to include explicit instructions on how to ensure this.

**Comment by brianhelba** [comment]
@mgrauer Regarding Python versions, were you asking about Python 2 vs 3, or about different version of Python 3 (e.g. 3.6 vs 3.7)?

Most of the role documentation was written around the primary concern of dealing with Python 2 vs Python 3, since both are commonly available on a system at the same time. I think we should update the docs to be more opinionated around encouraging people to just use Python 3 (although it will remain technically possible to use Python 2, just with more work offloaded to the user), which may further simplify things for the common case and prevent confusion.

Finally, note that part of the confusion may relate from the fact that there are two totally different contexts in which the Python version matters:
* The version of Python which we run Ansible under on the target machine
* The version of Python which Girder runs under

Things are much easier when both of these are the same version, so again, I'll update the docs to include explicit instructions on how to ensure this.

**Comment by mgrauer** [comment]
Does a read-only mirror mirror everything? e.g., is it possible to change the GH tagline at the top of the mirror to mention "this is a read only mirror of https://github.com/girder/girder/tree/master/devops/ansible-role-girder", or does that violate the mirroring?

**Comment by mgrauer** [comment]
> I think we should update the docs to be more opinionated around encouraging people to just use Python 3 (although it will remain technically possible to use Python 2, just with more work offloaded to the user), which may further simplify things for the common case and prevent confusion.

Yes I agree with this, let's be more opinionated about Python3 and that will partially help my confusion. And as I mentioned in the PR #3132 comments, the main question I was trying to answer by reading the docs of girder ansible role is, "what version of Python will Girder run under?".

**Comment by brianhelba** [comment]
> is it possible to change the GH tagline at the top of the mirror to mention "this is a read only mirror of

I just updated this.
