### ISSUE TITLE
Endpoint to get Item index within a folder.

### ISSUE THREAD

**Issue by BryonLewis** [girder/girder#3214]
Below I may not be using the proper terminology as it related to girder, please let me know where I am wrong.

The core request is an endpoint that will indicate the index of an item in a folder, given default or custom sorting/filtering parameters.

Base understanding:
- Within the base [collection/collections.js](https://github.com/girder/girder/blob/master/girder/web_client/src/collections/Collection.js) it handles pagination by requesting only 1 more than the limit that is indicated by the calling collection.  If it has more it will then indicate that there is more to show and then offset by the limit and grab the next page of data
- This doesn’t tell you a maximum number of pages, or what page and item is on, just that there is more data to show.

Request:
- Creation of an endpoint which allows for determining the position in the list for an item in a folder given sorting/filtering characteristics:

Reason:
- There exists users with large lists of images (10,000+) and to accurately navigate through a  browserWidget to their currently selected item it could take 100+ show more clicks.
- This would allow for a user to quickly navigate between subsets of a folder and not constantly rely on a +1 of the limit and an offset request.
- Would allow opening selected items in a hierarchyWidget directly to the page in which they are located.
-

**Comment by manthey** [comment]
Many paged endpoints return the total number of records as a custom header `Girder-Total-Count`.  This doesn't help know where in a list a record is located, but does allow determining how many pages there are.

**Comment by manthey** [comment]
I think the way to do this is to add an endpoint that mirrors the `GET item` endpoint.  This would be generalizable to any of our find endpoints (not just item).  The new endpoint (`GET item/:id/position` would take the same parameters as the find endpoint.  Internally, we can do the same query as find, but add to it {<sort field>: {'$lt' or '$gt' depending on sort order: item[<sort field]}}.  The count would then be the item's position.

Strictly, since we can sort by non-unique fields (name, for instance), this wouldn't quite be sufficient, as it would return the position of the first item with a matching name.  Since we only currently sort by one field, and the sort within matching items is undefined, this probably isn't strictly solvable.  We could redo the query with $lte/$gte starting at the position returned without the equality and determine the specific position as it happened to be returned in that query.  If the sort is stable, this would then be the actual position.

**Comment by manthey** [comment]
I've pushed a branch (not yet a PR) called `item-position`.

@brianhelba You've been the most opinionated recently.  Do you have any thoughts about this?  The main driving force is to improve the Browser Widget so when selecting from a very long list we can start on the correct page of data.  If there are no objections, I'll do the necessary work to make this into a PR.

**Comment by brianhelba** [comment]
To close the loop, I have no objections here. :smiley:
