### ISSUE TITLE
Add README item rendering to folder view

### ISSUE THREAD

**Issue by dchiquit** [girder/girder#3242]
When a folder contains an item called `README` (or variations like `README.txt` or `README.md`), viewing the folder in the web client should render the contents of the `README` under the metadata widget, similar to how GitHub will render `README`s when browsing repositories.

If possible, it should check for a `README` anywhere in the folder contents, not just the paginated contents that are currently being rendered.

I don't see any downside to having this feature, so I recommend it go into Girder Core. The only reason to provide a setting toggle would be if there is some kind of incompatibility with a plugin (perhaps the monkey brains project?), but fixing it in code would be a one time effort that would be part of this work.

**Comment by zachmullen** [comment]
We could do this with a query on items using parent folder ID and prefix regex (which will use the index), looking for a prefix of `README.`. Then we could infer the `content-type` based on the extension.

Unfortunately the existing `GET /item` endpoint doesn't allow prefix-based search by name, only exact match, so looking up multiple supported file extensions would involve 1 XHR per supported extension. So I don't think we'd want to do this with *only* front-end changes.

The two options I see are:

1. Add a new endpoint like `GET /folder/readme` that returns the contents of the file and includes the `content-type` for easy rendering. This would be nice since any front-end client could use it easily. I don't have strong feelings of whether that belongs in core vs. a small plugin.
2. Add a prefix-search flag to `GET /item` that allows us to use the existing compound index of `{folderId, name}`. This would be a core change, then we could do the rest on the client. However this involves more client-side work, so would not be easily adoptable by other front-end clients.

I'm leaning toward option 1.  Curious what others think.

**Comment by zachmullen** [comment]
Thinking about it more, I'd prefer the frontend changes to be in a plugin. Browsing folders is a very core operation of Girder, and lots of Girder instances will never want to do the README rendering, so we shouldn't incur the extra expense for those who don't want it.

**Comment by brianhelba** [comment]
> lots of Girder instances will never want to do the README rendering, so we shouldn't incur the extra expense for those who don't want it.

Do we expect that there are instances which include a README in a folder, yet would be frustrated if it rendered upon navigation to that folder? I expect that the rendering will happen below the hierarchy widget and will be asynchronous, so if this is disruptive / expensive to routine navigation, we've probably done something wrong with this feature regardless.

I don't feel strongly, but putting this into core would improve the discoverability of the feature and (purely subjectively to me) seems like a nice product enhancement.

**Comment by brianhelba** [comment]
Sorry, I meant product in the non-commercial sense. IMO, "it would be a nice enhancement to the usability of Girder core".

Consistency with the thumbnail plugin is a good point, but the image processing features of the thumbnail plugin require additional dependencies and potentially burden the server with more processing load. Contrariwise, any README functionality can just leverage the existing Markdown rendering libraries.

I wanted to talk through the alternatives of core vs plugin, but I also wouldn't object if it were in a plugin.

**Comment by dchiquit** [comment]
I don't have very strong opinions on the matter, but I think I'm leaning toward plugin just to be on the conservative side. I don't think the extra query would be very high impact if it were in core, but it is pure overhead for any instance that doesn't have any READMEs.

My chief qualm with a plugin is discoverability. I don't know how many end users would take the time to browse whatever plugin lists are available and install this particular plugin, even if they could stand to benefit. I guess it feels safer to slightly underserve users rather than bloat the application, but I could really go either way.

**Comment by mgrauer** [comment]
I'll agree with this going in a plugin, not out of a strong opinion, but to get @dchiquit unblocked and that seems a reasonable path forward.
