### ISSUE TITLE
ChangeLog appears to be outdated and gives wrong impression

### ISSUE THREAD

**Issue by hmeine** [girder/girder#3362]
Looking at https://girder.readthedocs.io/en/latest/changelog.html brings up a major question: Apparently, there were releases for 2.3.0, 2.4.0, 2.5.0, but nothing after that. Even though one can clearly see tags that seem to be releases (up until 3.1.5 ATM), the heading "Unreleased" after 2.5.0 makes the reader of the current documentation wonder if all subsequent versions visible as github tags, dockerhub tags, RTD versions, etc. should be considered "unreleased".

On Gitter, I was told that this impression is indeed wrong, so I herewith suggest to adapt the ChangeLog to either
* list current versions, or
* to indicate that the changelog is no longer maintained, but that recent releases can be found somewhere else (e.g., linking to GitHub).

**Comment by brianhelba** [comment]
Personally, I think
> indicate that the changelog is no longer maintained, but that recent releases can be found somewhere else

is the best option, as it less long-term effort, so we can focus our efforts on higher-impact maintenance.

Either way, I agree we should do something. No docs are better than misleading docs.

**Comment by f4str** [comment]
I agree that 

> indicate that the changelog is no longer maintained, but that recent releases can be found somewhere else

is most likely the best option. However, one concern is exactly where in GitHub to link. We can potentially link to the released page: [https://github.com/girder/girder/releases](https://github.com/girder/girder/releases), but I'm not too sure that this would exactly be particularly useful since it doesn't list any features like in the changelog (unless simply listing the release/version numbers is what we want).
