### ISSUE TITLE
Unicode in passwords are not supported by btoa

### ISSUE THREAD

**Issue by AlexanderKoehn** [girder/girder#3461]
User Story:
I want to use Umlaute in my password like 'ö'. So I set up a new account and want to login.

Behaviour:
Girder lets you create a user with a password that contains unicode, but the web login will not convert such a password to base64, since btoa cannot do that.
https://github.com/girder/girder/blob/d47bb163b6b539a55232d38fe537bb6d0531062a/girder/web_client/src/auth.js#L84

Solution:
Use 
`Buffer.from(username + ':' + password).toString('base64')`
instead of `window.btoa`

**Comment by zachmullen** [comment]
Hi @AlexanderKoehn , can you report which browser and version you are using, and how the error is manifesting? On latest chrome and Firefox, `btoa` supports the Latin1 character set (that seems to be the fixed-width single-byte charset those two browsers chose), which does contain these umlauted characters.

```javascript
window.atob(window.btoa('tschüß'))
'tschüß'
```

So my guess at the way this error is manifesting is that the server is what is throwing this error because it's attempting to decode the value as UTF8 and choking because it's receiving non-ASCII Latin1-encoded values. But it would be good if you could confirm this hypothesis.

All that said, I agree that we should support unicode in passwords, so switching to UTF8 encoding would be good. Your proposed solution won't work because `Buffer.from` is part of the node.js standard library, but not the browser's. We'd want to use [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) or something similar.

Would you like to make a PR for this?

**Comment by AlexanderKoehn** [comment]
ah my bad, the problem is that it gets encoded with Latin1, but in the backend you decode with utf-8:
https://github.com/girder/girder/blob/d47bb163b6b539a55232d38fe537bb6d0531062a/girder/api/v1/user.py#L108
And we have included Buffer as a polyfill, which I forgot.
And a non latin1 char throws an error: 
`btoa("username:╒")`

So this code should do it:
```
function b64EncodeUnicode(str) {
  // first we use encodeURIComponent to get percent-encoded Unicode,
  // then we convert the percent encodings into raw bytes which
  // can be fed into btoa.
  return btoa(
    encodeURIComponent(str).replace(/%([0-9A-F]{2})/g, function toSolidBytes(match, p1) {
      return String.fromCharCode('0x' + p1)
    })
  )
}
```

I will make a PR for it tomorrow

**Comment by zachmullen** [comment]
Great! This similar solution also seems to work and feels a bit more straightforward:

```javascript
function basicAuthEncode(username, password) {
    const utf8UintArray = new TextEncoder().encode(username + ':' + password);
    const base64String = [...utf8UintArray].map(byte => String.fromCharCode(byte)).join('');

    return 'Basic ' + btoa(base64String);
}
```

**Comment by AlexanderKoehn** [comment]
just changed my example code as soon as you posted ;)

**Comment by zachmullen** [comment]
Nice, yours is even better.

**Comment by AlexanderKoehn** [comment]
Made a PR but not sure, why the tests are failing:
https://github.com/girder/girder/pull/3463
