### ISSUE TITLE
girder-client stores files on /tmp, which might be too small for large files

### ISSUE THREAD

**Issue by siebenkopf** [girder/girder#3462]
When downloading an item via the command line interface, by default the file is first downloaded to a temporary file in the `TMPDIR`, before eventually being moved over to the target directory, cf. #1654

Now, my problem is that `/tmp` is rather small and downloading a large file raised a `no space left on device` exception.
I could solve this issue by setting:

```
TMPDIR=.
```

before calling the `girder-client`. I was wondering, why this intermediate step of saving to `TMPDIR` is necessary -- it also invokes a copy of the data when `TMPDIR` is on a different device as the target directory. The python `tempfile` library always allows to select a different directory for the temporary files (https://docs.python.org/3/library/tempfile.html), so it should be easy to set the target directory as `TMPDIR` to avoid the space issue and the data copy.

**Comment by zachmullen** [comment]
> I was wondering, why this intermediate step of saving to TMPDIR is necessary

It's a normal practice to download to a temporary file and then rename, to make sure that we don't partially overwrite a file and that the replacement is atomic. The `tempfile` module just provides a very simple way to do that in Python, so it's what we chose to use.

If we wanted, we could instead place the temporary file adjacent to its intended destination, by passing `dir` to `TemporaryFile`, but that would only be possible if the `path` argument to `downloadFile` was a path rather than a file handle.

Your setting of the environment variable is also a good workaround to use for this case.

**Comment by siebenkopf** [comment]
I am not exactly sure which `downloadFile` function you are referring to.
Anyway, the `girder-client` obtains a `download_folder` where the target items will be stored, cf: https://girder.readthedocs.io/en/latest/python-client.html#download-a-hierarchy-of-data-into-a-local-folder. 
You might want to use this as a default for the `TemporaryFile` directory. 

You could also estimate the directory of the file to be downloaded, create a temporary file in that folder, and move it to its original file name later on.

**Comment by zachmullen** [comment]
The function I'm referring to is here: https://github.com/girder/girder/blob/master/clients/python/girder_client/__init__.py#L1189

The fix I'm proposing would be to pass the `dir` argument to `NamedTemporaryFile`, setting it to the parent directory of the `path`. That would only be possible if the `path` was a path / string rather than a file-like object; the method supports both types.

**Comment by siebenkopf** [comment]
The only two function calls of this function https://github.com/girder/girder/blob/3ba508314d85a0e3469a2e6c5034058c2c89afee/clients/python/girder_client/__init__.py#L1259 and https://github.com/girder/girder/blob/3ba508314d85a0e3469a2e6c5034058c2c89afee/clients/python/girder_client/__init__.py#L1269 use path strings, only in your test cases, you pass other objects. Hence, in your implementation you can test whether it is a path and use its `os.path.dirname` as `dir` argument to `NamedTemporaryFile`, and `None` otherwise.

**Comment by zachmullen** [comment]
Yes, that is what I am proposing. Feel free to create a PR for this.

**Comment by siebenkopf** [comment]
I have no rights to create branches or PR directly here, and forking is too complex. Here is my solution to replace https://github.com/girder/girder/blob/e0a12ff2c5a74649833313ec2c374b8653390892/clients/python/girder_client/__init__.py#L1181 and following.

```
        # download to a tempfile
        progressFileName = fileId
        tempDir = None
        if isinstance(path, str):
            progressFileName = os.path.basename(path)
            # we use the current directory as temporary to avoid later data copying across devices
            # and to support files that are too large for the system's TEMPDIR
            tempDir = os.path.dirname(os.path.abspath(path))
            os.makedirs(tempDir, exist_ok=True)
```

**Comment by zachmullen** [comment]
I think your original workaround of setting `TMPDIR` in your environment is the best solution. I think the best code change to resolve this issue is to add some documentation around this; I can put in a PR to do so.

**Comment by zachmullen** [comment]
Rather than setting `TMPDIR=.`, set it to an absolute path on your filesystem that is distinct from the download destination. For example:

```bash
mkdir _tmp
TMPDIR=$(pwd)/_tmp girder-client ...
```

If that doesn't work, could you post the error you're seeing?
