### ISSUE TITLE
Make mongo read preference on replica sets configurable.

### ISSUE THREAD

**Issue by cpatrick** [girder/girder#412]

**Comment by manthey** [comment]
This can be specified in the mongodb URI.  Since we can now configure GridFS assetstores separately from the main girder db, you can use this to configure each one differently.  The URI parameter will override the default that we've selected (I haven't tested that, but other URI parameters override values we set on the MongoClient/MongoReplicaSetClient).

There are other Mongo settings that can be handled in the URI as well.  Rather than support each of them with a setting of ours, I think that handling the URI is sufficient.  Perhaps we should document that you can do this.  Otherwise, I'd recommend closing this issue.
