### ISSUE TITLE
Javascript documentation tool

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#420]
We should add something that builds or javascript docs automatically from code annotations. I've used [jsdoc](https://github.com/jsdoc3/jsdoc) for this in the past, but I recall it being rather crappy. If sphinx supports javascript, we should just use that.

**Comment by jbeezley** [comment]
I've done more exploring since this issue was last raised.  There are a few newer developments among javascript documentation generators.

* [dox](https://github.com/tj/dox) reads jsdoc style comments and outputs raw json.  The idea is that you can design your own templates to render it how you like.  It is a very nice project that does a much better job of generating consistent json than the [haruki](https://github.com/jsdoc3/jsdoc/tree/master/templates/haruki) jsdoc template.  The downside is that it doesn't use jsdoc and thus doesn't have full support for all jsdoc tags.  If we wanted to go the route of integrating the client-side documentation into our sphinx docs, this would probably be the way to go, but we would have to write the templates ourselves.
* A number of templates for rendering the output from dox have popped up as well,  but they all suffer from the limitations of dox itself.  To name a few in no particular order:
  * [dox-foundation](https://github.com/punkave/dox-foundation)
  * [mr-doc](https://github.com/mr-doc/mr-doc)
  * [markdox](https://github.com/cbou/markdox)
  * [doxumentor](https://github.com/dawnerd/doxumentor)
  * [dox-template](https://github.com/olivernn/dox-template)
  * [doxmate](https://github.com/JacksonTian/doxmate) (if you read Chinese)
  * [dox-basic](https://github.com/jepso/dox-basic)
  * [dox-docco](https://github.com/aearly/dox-docco)
* [documentation](https://github.com/documentationjs/documentation) is another (newer) generator that uses jsdoc style comments.  This one seems to be largely developed by the people behind mapbox and is under very active development.  It is what they use to generate their own top-notch [developer documentation](https://www.mapbox.com/mapbox-gl-js/api/).  I tried using it briefly on some of our projects.  It will definitely require some work to add the correct tags so that the documentation displays nicely, but I do have high hopes for it.

**Comment by zachmullen** [comment]
Thanks for looking into this! Since you are now the most informed about this subject, what tool would you recommend as the best one for us to move forward with? We don't have many constraints, since we don't really have anything at all currently.

**Comment by jbeezley** [comment]
Step one is to start adding consistent jsdoc style tags to all of our files.  The community has clearly settled on this as a standard.  We can't move forward with anything until we do that.  I've started doing this in GeoJS for the last 6 months or so.  

There are some issues regarding the conventions for the tags, i.e. how you nest things in namespaces and modules that will differ depending on what generator we end up on, but these won't be too difficult to fix once we do the initial work.  For backbone style inheritance, the style that I mentioned in my comment above works pretty well.

**Comment by jeffbaumes** [comment]
I think people will need some sort of documentation build to see/understand how their tagging will look when rendered as docs.

Looking at GitHub stars, jsdoc is 3x as high as both dox and documentation, which are neck-and-neck, but no rendering engine for dox has emerged (mr-doc is highest at 250 stars), so I'd put MapBox's documentation project ahead of dox if it were between those two.

Based on this I'd recommend setting up a basic jsdoc-based build which can be migrated to dox or documentation if desired later on.

**Comment by jbeezley** [comment]
Ideally, one shouldn't have to worry about how it will render when writing the docstrings.  If the docstrings are written correctly, how it renders is almost entirely determined by the template you use.  There are tools to validate the docstrings as well.  For geojs, I have a travis test that just executes `jsdoc --pedantic` to prevent major problems.  ESLint will check docstrings with a standard [rule](http://eslint.org/docs/rules/valid-jsdoc.html) and there is a [plugin](https://github.com/gajus/eslint-plugin-jsdoc) which will do more validation.

One of the great things about using the jsdoc annotation standard is that we can switch between them fairly easily.  I agree that before we can reasonably require everyone to do this we should set up an initial system for it with a few important base classes well documented.  jsdoc is definitely the *easiest* way to get started, though my impression is that it is more difficult to write templates to customize the output.

**Comment by jbeezley** [comment]
I just ran across [jsdoced](https://github.com/jeromeetienne/jsdoced.js).  It adds testing of argument and return type annotations as well as asserting `@private` tags are respected.  I don't know that I would use the generated code in production, but it would be interesting to use it for running the unit tests or even just manual testing from time to time.

**Comment by zachmullen** [comment]
I'm going to close this since we now have a solution in place, albeit an incomplete one. https://doc.esdoc.org/github.com/girder/girder/

We can open separate issues to change this solution or improve the docs.
