### ISSUE TITLE
size quota plugin

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#474]
Should allow the enforcement of maximum sizes per collection and user.

**Comment by manthey** [comment]
Policy question: Obviously, admins can change quotas for any collection or user.  No one but an admin can change the quota for a user.  Can an owner on a collection change the quota if that owner is NOT an admin?

I think not, as then a non system-admin has powers to affect how much quota is used, but I wanted to know what someone else though.

**Comment by cpatrick** [comment]
My opinion is that only site admins control quotas as it is management of a
system resource.

-Patrick

**Comment by zachmullen** [comment]
:+1:

**Comment by zachmullen** [comment]
@manthey we have this feature in Midas, and I think this one should be quite similar. In Midas, we have two system settings for the quota plugin, a default user quota and a default collection quota. Empty value meant unlimited. On each collection page and each user profile page we can add a UI like in the screenshot attached to allow overrides for individual users.

![screen shot 2015-01-06 at 10 26 27 am](https://cloud.githubusercontent.com/assets/555959/5630770/bab7c522-958e-11e4-934d-ea519603b40f.png)

**Comment by zachmullen** [comment]
I like the idea of resource-level admin access being required in order to *view* the quota, i.e. users can see their own quota and collection admins can see the collection quota, but others cannot. I'm open to other opinions on that though.

**Comment by manthey** [comment]
I have the quota stuff fully working on collections and users.  I don't have a pie chart (or even a current report on the used space).  I've done this as a plugin.

I have also implemented a 'preferred assetstore' and 'fallback assetstore' for users and collections as well (so that all new uploads for that user go to a specific assetstore; if the assetstore is offline, it goes to the fallback).  The preferred and fallback assetstores default to the current assetstore, and the fallback can be set to none, to disallow uploads if the preferred assetstore is unavailable.  Eventually, I'd like assetstores to be marked unavailable when they are full.

At the moment, only general admins can see the quotas.

![menu](https://cloud.githubusercontent.com/assets/8781639/5630881/ced6c1a6-958f-11e4-886b-637c1b040d28.png)
![dialog](https://cloud.githubusercontent.com/assets/8781639/5630884/d3213caa-958f-11e4-9e82-2910835992aa.png)

For what I set out to do, all I have left is to write tests for the UI.

I think adding the currently used amount and also access to resource-level admins so that they can view the policies is a good idea.

**Comment by zachmullen** [comment]
Wow, awesome! Have you implemented the behavior of disallowing an upload if it would overflow the quota?

**Comment by manthey** [comment]
Yes.  The checks are done when starting and also when finishing (so that two uploads that would both fit can be started, but only the one the completes first gets in).

**Comment by manthey** [comment]
![overlimit](https://cloud.githubusercontent.com/assets/8781639/5630981/bef03dd4-9590-11e4-891e-3420156733bb.png)

Perhaps I should format those numbers in a nice way, rather than leave them as just the number of bytes.

**Comment by zachmullen** [comment]
We can actually validate the file selection before they even hit start upload by wrapping `filesChanged` and adding some behavior after to sum up the size of `this.files` and conditionally calling `this.setUploadEnabled(false)`. In the above screenshot, it looks like they don't get shown the button to re-select files, which might be helpful so they could at least upload part of what they wanted.

**Comment by zachmullen** [comment]
I don't actually care if it happens before or after they hit the start button, so long as we revert to the state that will let them re-select files. :smile:

**Comment by jeffbaumes** [comment]
When it comes time for pie charts, let's do it right with D3 (maybe donut chart instead?). No need for older browser compatibility with Girder and with D3 we can make it very clean-looking and have the style/font match the Girder UI. I'd be glad to help!

**Comment by manthey** [comment]
Currently, we are using jqplot for the pie chart on the assetstore page.  If we use D3, we should change the assetstore page, too.

I'd like to add this later today, so any advice or samples are welcome.

**Comment by cpatrick** [comment]
Is there a prefered layer atop D3 that we can use? JQPlot has an awesome
API compared to mucking with SVG. Not all of us are D3 Ninjas ;).

-Patrick

**Comment by jeffbaumes** [comment]
Since I don't have time to work on this right now - you should maybe go ahead and use jqplot if we are already depending on it. I can put a task to update the plots when I feel motivated to do so. @cpatrick Yes there is something to say for maintainability. I won't go off and do something before thinking it over. Tangelo.js may be the "layer" we want with easy-to-use D3 components. NVD3 would be another choice that I think looks nicer than jqplot.

**Comment by cpatrick** [comment]
@jeffbaumes :+1: Though my past experiences with nvd3 have been.. mixed.

**Comment by zachmullen** [comment]
FWIW, by removing the wonky shadows, background colors, and gratuitous borders, we managed to get something cleaner in girder using jqplot:

![screen shot 2015-01-06 at 11 30 29 am](https://cloud.githubusercontent.com/assets/555959/5631820/9d647336-9597-11e4-8a8a-fea892368ffa.png)

I'm fine either way, we already have both d3 and jqplot available.

**Comment by jeffbaumes** [comment]
I've not used NVD3 so can't speak for its utility - just looks clean. If I were coding a chart I would like a high-level API but would also want total control over the underlying code if needed. That's a plus of tangelo.js - if there was a bug or we needed to add behavior we'd be able to update the underlying library ourselves. Also would be dogfooding :dog:.

@zachmullen yes that looks a bit better.

**Comment by zachmullen** [comment]
Doesn't necessarily need to be on this topic branch, but I'm all for using tangelo.js within girder any place that we can.

**Comment by cpatrick** [comment]
+100000 to reusable js charts in tangelo.js and using that in girder.

-Patrick

**Comment by manthey** [comment]
Added in PR #603.
