### ISSUE TITLE
Emails show incorrect URL

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#614]
I think this is due to being behind a proxy, I saw this from data.kitware.com. The text of the email was:

Your password has been reset. Your new password is: ...

If you did not initiate this password reset, please contact a site administrator.

This auto-generated email sent from Girder @ http://0.0.0.0:8080.

**Comment by zachmullen** [comment]
We should fix #615 and use those utilities to fix this issue.

**Comment by manthey** [comment]
I see two parts to this: (a) the host and port that the email is generated from, and (b) the url that is provided for the user to get back to girder.

The url (b) is generated from the host (or X-Forwarded-Host) and the base path for girder.  I think that is generated appropriately, but we could override it (which is what I interpreted issue #615 to be).  In the event that girder isn't served in the normal spot, this should move appropriately as well.  The only issue I think it would have is that if a plugin wants that callback to route somewhere other than the standard girder web client.

The host (a) is currently taken from the cherrypy local name.  The local name doesn't really look like it will ever be useful.  Since the goal of this field is to let the user know where the email originated, I think this has to be a setting, much like the email-from-address.

**Comment by zachmullen** [comment]
As much as I prefer automated detection, I think you're right and we'll probably save ourselves headaches by simply making it a system setting (two system settings, to address #615).

**Comment by cpatrick** [comment]
Cool! Now that we've decided to make it configurable, we can argue over the default. :smile_cat:

**Comment by manthey** [comment]
The cherrypy local host is ([global] server.socket_host):([global] server.socket_port).  If unspecified, this can be the default (as it is currently).  There, I've started the argument. :crocodile:

**Comment by manthey** [comment]
How much validation should we enforce on this value?  It is currently just shown as a link at the bottom of emails, so the value doesn't have to really be anything sensible, but we could choose to make sure it is of the form (schema)://(host).  We might want to be more liberal that that, too, since it could be used as a link back to an about or help page.

**Comment by manthey** [comment]
Added is PR #620.
