### ISSUE TITLE
Investigate alternative js coverage tools

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#623]
Blanket seems to be a dead project, and may be causing some of our intermittent test failures.

**Comment by manthey** [comment]
I have been investigating the intermittent web client test failures.  When I remove blanket from the mix, it definitely reduces the errors (see below).

Removing blanket wasn't as straightforward as I hoped.  We are relying on the javascript being loaded AFTER testenv.html to properly start the web app.  Specifically, we want to read the apiRoot and staticRoot, but these are set in javascript before the document where they are stored is rendered by phantom.  Since blanket loads all the covered scripts a second time, the second time they load, the DOM already contains these values and everything works.

Secondly, without blanket, jasmine tries to run its tests before they are loaded.  It probably has something to do with the way we use injectJS to load the spec file, rather than loading it as part of the html.  In my tests, I've added a loop to wait for the spec tests to load before starting jasmine (which has the drawback that if we ever specify a spec file with no enabled `describe()` functions, the method will hang).

With blanket disabled, I still see that the retry process is necessary for the times that phantom fails to load javascript.  I also see occasions where the Jasmine runner never starts.  We can retry here, too (but sometimes this fails multiple times).

I have NOT seen failures once the tests start to run properly.  However, this could be just that blanket slows things down enough that sometimes our tests time out or fail when we assume that they will be ready in a certain way.  That is, I'm not convinced blanket is the culprit rather than a victim.

**Comment by manthey** [comment]
At least one of the intermittent failures occurs because a port we want for testing is in use.  I *think* that this is because we are using ports greater than 49152, so that the ports have a chance of being used as ephemeral ports.  cherrypy always opens its port with SO_REUSEADDR, so it shouldn't ever have a problem reusing the same port in back-to-back tests.  I'm trying my tests again with ports below the ephemeral range to see if that clears up some of the intermittent issues.
