### ISSUE TITLE
Pip installing latest girder package does not work if girder package is on PYTHONPATH

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#625]
Following the instructions here: http://girder.readthedocs.org/en/latest/development.html#creating-a-new-release

Everything went fine, and then I reached step 5 and successfully ran

```
pip install ../girder/girder-1.2.0.tar.gz
```

Which installed all the dependencies and finally yielded the following message:

```
Successfully installed cffi CherryPy pymongo bcrypt boto Mako PyYaml requests psutil pycparser MarkupSafe
```

It had installed all the dependencies in the virtualenv, but not girder itself. When I unset my PYTHONPATH so that the girder package from my source tree was no longer on it, and re-ran the install, it installed girder successfully.

**Comment by jbeezley** [comment]
That's odd.  I suspect it might be pip bug.  I'll see what I can find out.

**Comment by jbeezley** [comment]
I think this is intended behavior.  For a clean virtualenv with `PYTHONPATH` set to the girder repository, this is what you have.

```
$ pip freeze
-e git+https://github.com/girder/girder.git@8691b90e34056d6f6452f4e19fb867f430935c40#egg=girder-v1.2.0
```

It is interpreting the girder repo directory as a "editable" pip install, so it interprets girder as already installed.  In fact, it isn't even the `girder` package being in `PYTHONPATH` that is causing it to think this; it is the presence of `girder.egg-info` that is created when running `python setup.py sdist`, which is what happens when running `pip install -e`.

We _could_ delete `girder.egg-info` at the end of `grunt package` to prevent this, but I think ultimately it is  necessary to be careful with `PYTHONPATH`.

**Comment by zachmullen** [comment]
That's what I was seeing too. I guess the problem is that when you get to that state, `girder-install` is not on the path, but maybe we can live with that and close this one out.

**Comment by jbeezley** [comment]
Running `pip install -U ../girder/girder-1.2.0.tar.gz` would probably do what you want as well.  Actually, it is probably better to always install with `-U` otherwise the version number of dependences won't be respected if they happen to be installed already.

I'll leave it up to you to close.
