### ISSUE TITLE
change markdown library

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#715]
The current library has xss issues.

https://github.com/evilstreak/markdown-js/issues/235

**Comment by ixti** [comment]
I suggest you to switch to [markdown-it](https://github.com/markdown-it/markdown-it).
Otherwise it looks like [changing one problem to another](https://github.com/chjj/marked/issues/497). :D

**Comment by zachmullen** [comment]
@ixti thanks for the suggestion, we actually looked into markdown-it but considered it too heavy-weight of a footprint, since all we need is client-side rendering. The author currently has no plans to make a lighter weight browser-only subset, so for now we are going to use marked. The vulnerability you linked is acceptable to us since the markdown rendering incurs no computational overhead on our servers.

**Comment by mhuggins** [comment]
I don't think the marked library solved your problem either.  This string allows me to execute JS just as well:

```
[show alert](javascript:alert("hi"&#41;)
```

**Comment by mhuggins** [comment]
Never mind, I failed to read all the way through your comments.  Carry on. :)
