### ISSUE TITLE
girder-cli throws type error when given an invalid scheme

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#934]
Calling the girder-cli similarly to this:
```
girder-cli  --host some.girder-install.com --username "foo" --password "bar" -c upload 
55882fe58d777fa4919ba1d1 playbook.retry 
```

Where some.girder-install.com is configured to use https, yields the following output:

```
Uploading Item from playbook.retry
Traceback (most recent call last):
  File "/usr/local/bin/girder-cli", line 9, in <module>
    load_entry_point('girder-client==1.0.2', 'console_scripts', 'girder-cli')()
  File "/usr/local/lib/python2.7/dist-packages/girder_client/cli.py", line 96, in main
    reuse_existing=args.reuse)
  File "/usr/local/lib/python2.7/dist-packages/girder_client/__init__.py", line 897, in upload
    current_file, reuse_existing)
  File "/usr/local/lib/python2.7/dist-packages/girder_client/__init__.py", line 764, in _upload_as_item
    local_file, current_item['_id'], file_path)
TypeError: list indices must be integers, not str
```

Adding ```--scheme https``` to the above command causes it to run correctly.

**Comment by zachmullen** [comment]
This is actually due to a misconfiguration of data.kitware.com in particular. It redirects the http: scheme to https:, but incorrectly uses the 302 status rather than the 307 status. If a 307 is used, that instructs clients to reuse the same method they used to make the initial request; in the 302 case, well-behaved clients will convert the request to a GET, which is why a list was returned. I'm going to close this issue and ping sysadmin about that instance.
